### ISSUE TITLE
Nil pointer deref on "test_data" folder (not the "_")

### ISSUE THREAD

**Issue by Quasilyte** [go-lintpack/lintpack#65]
From logs:
```
istio.io/istio/mixer/test/client/test_data
processed 15369/18024 (85.27%)...
2019/01/26 12:29:04 ERROR: exit status 2: panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x77d6d3]

goroutine 1 [running]:
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).loadProgram.func1(0x1, 0x0, 0xc00018dac0)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:258 +0x33
sort.insertionSort_func(0xc00018dbb8, 0xc00017e7e0, 0x0, 0x2)
	$GOROOT/go/src/sort/zfuncversion.go:12 +0x93
sort.stable_func(0xc00018dbb8, 0xc00017e7e0, 0x2)
	$GOROOT/go/src/sort/zfuncversion.go:171 +0x86
sort.SliceStable(0x7e5140, 0xc00017e7c0, 0xc00018dbb8)
	$GOROOT/go/src/sort/slice.go:31 +0x106
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).loadProgram(0xc0000c8300, 0x0, 0x0)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:257 +0x233
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.(*linter).loadProgram-fm(0x0, 0x0)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:41 +0x2a
github.com/go-lintpack/lintpack/linter/lintmain/internal/check.Main()
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/internal/check/check.go:48 +0x324
github.com/go-lintpack/lintpack/internal/cmdutil.DispatchCommand(0xc0000b5f40, 0x3, 0x3)
	$GOPATH/src/github.com/go-lintpack/lintpack/internal/cmdutil/cmdutil.go:49 +0x184
github.com/go-lintpack/lintpack/linter/lintmain.Run(0x8610ca, 0x5, 0x861daa, 0x8)
	$GOPATH/src/github.com/go-lintpack/lintpack/linter/lintmain/lintmain.go:63 +0x46a
main.main()
	/tmp/linter034045433.go:11 +0x4b
```

**Comment by Quasilyte** [comment]
It is something that may lead to https://github.com/go-toolsmith/pkgload/issues/6.
